### ISSUE TITLE
Last row of pictures crop from bottom

### ISSUE THREAD

**Issue by DavidIsrawi** [SammyIsra/SammyPortfoliov2#9]
Issue
- Last row of pictures are not displaying fully, cropped from the bottom

Repro
- Check last row of pictures

Env
- Mac OS
- Chrome 72.0

<img width="1383" alt="Screen Shot 2019-03-17 at 1 58 21 PM" src="https://user-images.githubusercontent.com/13784628/54497945-04060400-48be-11e9-8038-84a9ee2d60da.png">

**Comment by SammyIsra** [comment]
This seems to be related to an issue someone found on Chrome where the first row "blinks" a couple of images. 

I believe this has to do with `gatsby-image` and the way it renders images, so I have filed an issue with Gatsby regarding `gatsby-image` here: https://github.com/gatsbyjs/gatsby/issues/12676

I'll follow the conversation on that page.
